### ISSUE TITLE
Example kann nicht im example ordner kompiliert werden

### ISSUE THREAD

**Issue by DiSiKi** [ACON-Kiel/beamer#2]
Um example.tex zu kompilieren müssen die Pfade korrigiert werden.

Lösung:

1. example.tex in Hautpordner verschieben
2. Pfade in example.tex ändern

**Comment by tmeurer** [comment]
This is not the case. You need to add the lrt-beamer folder (the examples folder can be placed wherever you like) to you local tex path and update the database. In Linux this is typically the folder $home/texmf, where (according to the LaTeX path conventions) one has to place lrt-beamer into the subfolder $home/texmf/tex/latex. Then run mktexlsr to update the DB. When using Miktex under Windows you need to place the lrt-beamer folder into the localtexmf folder specified in the Miktex configuration.
